#!/usr/bin/env python3

import sys

from rqt_gui.main import Main


PLUGIN = 'motion_control_rqt.motion_control_controller.MotionControlController'


def main():
    rqt_main = Main(filename=PLUGIN)
    return rqt_main.main(standalone=PLUGIN)


if __name__ == '__main__':
    sys.exit(main())
