period: 1000000

masters:
  - id: 0
    type: serial
    number_of_slaves: 1
    serial_port: /dev/ttyUSB0
    serial_baudrate: 1000000
    slaves:
      - controller_index: 0
        driver_id: 0
        can_id: 1
        profile_mode: 0 # 0: Position Mode, 1: Velocity Mode, 2: Effort Mode

drivers:
  - id: 0
    pulse_per_revolution: 4096
    rated_effort: 1193.0
    unit_effort: 1.0
    lower: -180.0
    upper: 180.0
    speed: 343.7746770785
    acceleration: 1145.9155902616
    deceleration: 1145.9155902616
    profile_velocity: 171.8873385392
    profile_acceleration: 1145.9155902616
    profile_deceleration: 1145.9155902616
    profile_position_value: 3
    profile_velocity_value: 1
    profile_effort_value: 0
    type: dynamixel
    param_file: ../param/dynamixel/xm430_w350.yaml
