period: 1000000

masters:
  - id: 0
    type: canopen
    number_of_slaves: 1
    can_interface_index: 0 # can0
    can_bitrate: 1000000
    slaves:
      - controller_index: 0
        driver_id: 0
        can_id: 1
        profile_mode: 0 # 0: Position Mode, 1: Velocity Mode, 2: Effort Mode

drivers:
  - id: 0
    pulse_per_revolution: 524288
    zero_offset: 0
    gear_ratio: 1.0
    rated_effort: 25.0
    unit_effort: 0.001
    lower: -57.2957795131
    upper: 57.2957795131
    speed: 2000
    acceleration: 85.9436692696
    deceleration: 85.9436692696
    profile_velocity: 85.9436692696
    profile_acceleration: 85.9436692696
    profile_deceleration: 85.9436692696
    profile_position_value: 1
    profile_velocity_value: 3
    profile_effort_value: 4
    type: zeroerr
    param_file: package://motor_manager/hardware/zeroerr/param
