#!/usr/bin/env python3

from rqt_gui.main import Main
from rqt_motion_control.motion_control_controller import MotionControlController

import sys


plugin = 'rqt_motion_control.motion_control_controller.MotionControlController'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
